services:
  # mysql:
  #   image: mysql:8.0
  #   container_name: mysql-container
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root_pass
  #     MYSQL_DATABASE: tododb
  #     MYSQL_USER: appuser
  #     MYSQL_PASSWORD: app_pass
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql-data:/ver/lib/mysql
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_pass"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 10

  java-app:
    ports:
      - "8080:8080"
    build: .
    container_name: java-container
#     depends_on:
#       mysql:
#         condition: service_healthy

# volumes:
#   mysql-data: